version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: .app/:/usr/src/app/
    ports: 8000:8000
    user: ${CURRENT_UID}
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    volumes: .api/:/usr/src/api/
    ports: 80:8888
    user: ${CURRENT_UID}
