version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/src/app/
    ports: 
      - 80:8000
    user: ${CURRENT_UID}
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    volumes: 
      - ./api/:/usr/src/api/
    ports: 
      - 8888:8888
    user: ${CURRENT_UID}
